# Generated by Django 4.2.28 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding_core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardingday",
            name="task_templates",
            field=models.JSONField(blank=True, default=list, verbose_name="Task templates"),
        ),
    ]
