# Generated by Django 4.2.x on 2026-02-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding_core", "0002_alter_onboardingmaterial_options_and_more"),
        ("onboarding_core", "0002_onboardingday_task_templates"),
    ]

    operations = []
