# Generated by Django 4.2.27 on 2026-02-28 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_merge_0003_branches"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reason", models.TextField(blank=True, verbose_name="Причина")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("review_comment", models.TextField(blank=True, verbose_name="Комментарий проверки")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата проверки")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "requested_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotion_requests",
                        to="accounts.role",
                        verbose_name="Запрошенная роль",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_promotion_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Проверил",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на повышение",
                "verbose_name_plural": "Заявки на повышение",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="promotionrequest",
            index=models.Index(fields=["status"], name="accounts_pr_status_b48362_idx"),
        ),
        migrations.AddIndex(
            model_name="promotionrequest",
            index=models.Index(fields=["user"], name="accounts_pr_user_id_839a2f_idx"),
        ),
    ]
