# Generated by Django 4.2.27 on 2026-02-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_auditlog_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Intern'), (20, 'Employee'), (30, 'Administrator'), (31, 'Admin'), (40, 'SuperAdmin')], default=10, verbose_name='Уровень'),
        ),
    ]
