# Generated by Django 4.2.x on 2026-02-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_promotion_request"),
        ("accounts", "0007_alter_role_level"),
    ]

    operations = []
