# Generated by Django 4.2 on 2026-03-02 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_role_hierarchy_update"),
        ("accounts", "0008_merge_20260228_1348"),
    ]

    operations = []

