# Generated by Django 4.2.27 on 2026-03-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_set_backend_spec_url'),
        ('accounts', '0010_department_comment_alter_role_level'),
    ]

    operations = [
    ]
