from django.urls import path
from .views import (
    ProductionCalendarDayAdminAPIView,
    ProductionCalendarMonthGenerateAPIView,
    WorkScheduleListAPIView,
    WorkScheduleAdminListCreateAPIView,
    WorkScheduleAdminDetailAPIView,
    WorkScheduleRequestListAPIView,
    WorkScheduleRequestDecisionAPIView,
    WorkScheduleAdminAssignAPIView,
    WorkScheduleTemplateUsersAPIView,
    MyScheduleAPIView,
    ScheduleOptionsAPIView,
    CalendarView,
    ChooseScheduleAPIView,
    CalendarMonthAPIView,
    WeeklyWorkPlanAdminDecisionAPIView,
    WeeklyWorkPlanAdminChangesAPIView,
    WeeklyWorkPlanAdminListAPIView,
    WeeklyWorkPlanMyChangesAPIView,
    WeeklyWorkPlanMyAPIView,
)

urlpatterns = [
    # New v1 endpoints
    path("v1/work-schedules/", WorkScheduleListAPIView.as_view()),
    path("v1/work-schedules/my/", MyScheduleAPIView.as_view()),
    path("v1/work-schedules/select/", ChooseScheduleAPIView.as_view()),
    path("v1/work-schedules/calendar/", CalendarView.as_view()),
    path("v1/work-schedules/weekly-plans/my/", WeeklyWorkPlanMyAPIView.as_view()),
    path("v1/work-schedules/weekly-plans/my/changes/", WeeklyWorkPlanMyChangesAPIView.as_view()),
    path("v1/work-schedules/admin/weekly-plans/", WeeklyWorkPlanAdminListAPIView.as_view()),
    path("v1/work-schedules/admin/weekly-plans/<int:plan_id>/decision/", WeeklyWorkPlanAdminDecisionAPIView.as_view()),
    path("v1/work-schedules/admin/weekly-plans/<int:plan_id>/changes/", WeeklyWorkPlanAdminChangesAPIView.as_view()),
    path("v1/work-schedules/admin/templates/", WorkScheduleAdminListCreateAPIView.as_view()),
    path("v1/work-schedules/admin/templates/<int:schedule_id>/", WorkScheduleAdminDetailAPIView.as_view()),
    path("v1/work-schedules/admin/templates/<int:schedule_id>/users/", WorkScheduleTemplateUsersAPIView.as_view()),
    path("v1/work-schedules/admin/requests/", WorkScheduleRequestListAPIView.as_view()),
    path("v1/work-schedules/admin/requests/<int:request_id>/decision/", WorkScheduleRequestDecisionAPIView.as_view()),
    path("v1/work-schedules/admin/assign/", WorkScheduleAdminAssignAPIView.as_view()),
    path("v1/work-schedules/admin/calendar/day/", ProductionCalendarDayAdminAPIView.as_view()),
    path("v1/work-schedules/admin/calendar/generate/", ProductionCalendarMonthGenerateAPIView.as_view()),

    # Legacy compatibility
    path("my-schedule/", MyScheduleAPIView.as_view()),
    path("schedules/", ScheduleOptionsAPIView.as_view()),
    path("calendar/", CalendarView.as_view(), name="calendar"),
    path("calendar-month/", CalendarMonthAPIView.as_view()),
    path("choose-schedule/", ChooseScheduleAPIView.as_view()),
]
