# Generated by Django 4.2.27 on 2026-03-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_notification_event_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='notificationtemplate',
            options={'verbose_name': 'Notification template', 'verbose_name_plural': 'Notification templates'},
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='common_noti_code_9f8b64_idx',
            old_name='cmn_notif_code_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='common_noti_severit_cdbb76_idx',
            old_name='cmn_notif_severity_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='common_noti_entity__b17f85_idx',
            old_name='cmn_notif_entity_type_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='common_noti_entity__9c8766_idx',
            old_name='cmn_notif_entity_id_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('system', 'System'), ('learning', 'Learning'), ('info', 'Info')], default='info', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='type',
            field=models.CharField(choices=[('system', 'System'), ('learning', 'Learning'), ('info', 'Info')], max_length=50),
        ),
    ]
