# Generated by Codex on 2026-03-18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_alter_notification_options_and_more"),
        ("common", "0002_notification_runtime_fields"),
    ]

    operations = []

