# Generated by Django 4.2.28 on 2026-02-27 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_merge_0003_branches'),
    ]

    operations = [
        migrations.CreateModel(
            name='KBCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='kb.kbcategory')),
            ],
            options={
                'ordering': ['name', 'id'],
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='KBArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('visibility', models.CharField(choices=[('all', 'All'), ('department', 'Department'), ('role', 'Role')], default='all', max_length=20)),
                ('role_name', models.CharField(blank=True, choices=[('SUPER_ADMIN', 'SuperAdmin'), ('ADMIN', 'Admin'), ('TEAMLEAD', 'TeamLead'), ('EMPLOYEE', 'Employee'), ('INTERN', 'Intern')], max_length=32, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='kb.kbcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_articles_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_articles', to='accounts.department')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KBViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='kb.kbarticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_view_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at', '-id'],
                'indexes': [models.Index(fields=['article', 'viewed_at'], name='kb_kbviewlo_article_dcf7f4_idx'), models.Index(fields=['user', 'viewed_at'], name='kb_kbviewlo_user_id_6ea2fa_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='kbarticle',
            index=models.Index(fields=['visibility'], name='kb_kbarticl_visibil_4fae24_idx'),
        ),
        migrations.AddIndex(
            model_name='kbarticle',
            index=models.Index(fields=['is_published'], name='kb_kbarticl_is_publ_9f2afb_idx'),
        ),
        migrations.AddIndex(
            model_name='kbarticle',
            index=models.Index(fields=['department'], name='kb_kbarticl_departm_eaed56_idx'),
        ),
        migrations.AddIndex(
            model_name='kbarticle',
            index=models.Index(fields=['role_name'], name='kb_kbarticl_role_na_3e4b8e_idx'),
        ),
    ]
