# Generated by Django 4.2.27 on 2026-02-17 09:57

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='Подразделение')),
                ('telegram', models.CharField(blank=True, help_text='Например: @username', max_length=50, verbose_name='Telegram')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('position_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_management', models.BooleanField(default=False, verbose_name='Руководство')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['position_order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('complaint', 'Жалоба'), ('suggestion', 'Предложение'), ('review', 'Отзыв')], max_length=20)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('closed', 'Закрыто')], default='new', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('kg', 'Кыргызча')], default='ru', max_length=5, verbose_name='Язык')),
                ('type', models.CharField(choices=[('text', 'Текст'), ('link', 'Ссылка'), ('file', 'Файл')], max_length=10, verbose_name='Тип инструкции')),
                ('text', models.TextField(blank=True, verbose_name='Текст инструкции')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('file', models.FileField(blank=True, null=True, upload_to='instructions/', verbose_name='Файл')),
                ('is_active', models.BooleanField(default=False, verbose_name='Актуальная инструкция')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Инструкция',
                'verbose_name_plural': 'Инструкции',
                'unique_together': {('language', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='LanguageSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('kg', 'Кыргызча')], max_length=5, unique=True, verbose_name='Язык')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включён')),
            ],
            options={
                'verbose_name': 'Язык интерфейса',
                'verbose_name_plural': 'Языки интерфейса',
            },
        ),
        migrations.CreateModel(
            name='NewsSliderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoplay', models.BooleanField(default=True, verbose_name='Автопрокрутка')),
                ('autoplay_delay', models.PositiveIntegerField(default=5000, help_text='Задержка в миллисекундах', verbose_name='Задержка (мс)')),
            ],
            options={
                'verbose_name': 'Настройки слайдера новостей',
                'verbose_name_plural': 'Настройки слайдера новостей',
            },
        ),
        migrations.CreateModel(
            name='WelcomeBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('language', models.CharField(default='RU', max_length=10)),
                ('order', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.instruction')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('ru', 'RU'), ('en', 'EN'), ('kg', 'KG')], default='ru', max_length=2, verbose_name='Язык')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('short_text', models.CharField(blank=True, max_length=255, verbose_name='Краткое описание')),
                ('full_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Полный текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Изображение')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['position', '-published_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='welcomeblock',
            constraint=models.UniqueConstraint(fields=('order', 'language'), name='unique_order_per_language'),
        ),
    ]
