# Generated by Django 4.2.27 on 2026-02-21 10:57

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_course_courseenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='full_text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Full text'),
        ),
    ]
