# Generated by Django 4.2.27 on 2026-02-25 14:45

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_feedback_sender_recipient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
        migrations.AlterModelOptions(
            name='welcomeblock',
            options={'ordering': ['order'], 'verbose_name': 'Приветственный блок', 'verbose_name_plural': 'Приветственные блоки'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='recipient',
            field=models.CharField(choices=[('ADMIN', 'To admin'), ('SUPER_ADMIN', 'To super admin')], default='ADMIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('new', 'РќРѕРІРѕРµ'), ('in_progress', 'Р’ СЂР°Р±РѕС‚Рµ'), ('accepted', 'РџСЂРёРЅСЏС‚Рѕ')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='news',
            name='full_text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Полный текст'),
        ),
        migrations.AlterField(
            model_name='welcomeblock',
            name='language',
            field=models.CharField(default='ru', max_length=10),
        ),
    ]
