# Generated by Django 4.2.28 on 2026-02-27 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StepTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('role_responsible', models.CharField(choices=[('SUPER_ADMIN', 'SuperAdmin'), ('ADMIN', 'Admin'), ('TEAMLEAD', 'TeamLead'), ('EMPLOYEE', 'Employee'), ('INTERN', 'Intern')], max_length=32)),
                ('requires_comment', models.BooleanField(default=False)),
                ('sla_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('process_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='bpm.processtemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('process_template', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ProcessInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_process_instances', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='bpm.processtemplate')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StepInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('process_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='bpm.processinstance')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_instances_responsible', to=settings.AUTH_USER_MODEL)),
                ('step_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='step_instances', to='bpm.steptemplate')),
            ],
            options={
                'ordering': ['step_template__order', 'id'],
                'indexes': [models.Index(fields=['status'], name='bpm_stepins_status_7baf60_idx'), models.Index(fields=['responsible_user', 'status'], name='bpm_stepins_respons_79295e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='processinstance',
            index=models.Index(fields=['status'], name='bpm_process_status_1dc590_idx'),
        ),
        migrations.AddIndex(
            model_name='processinstance',
            index=models.Index(fields=['created_by', 'created_at'], name='bpm_process_created_b3f985_idx'),
        ),
    ]
