# Generated by Django 4.2.27 on 2026-03-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steptemplate',
            name='role_responsible',
            field=models.CharField(choices=[('SUPER_ADMIN', 'SuperAdmin'), ('ADMINISTRATOR', 'Administrator'), ('ADMIN', 'Admin'), ('TEAMLEAD', 'TeamLead'), ('EMPLOYEE', 'Employee'), ('INTERN', 'Intern')], max_length=32),
        ),
    ]
