# Generated by Django 4.2.27 on 2026-02-08 21:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('type', models.CharField(choices=[('link', 'Link'), ('file', 'File')], max_length=10, verbose_name='Тип регламента')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('file', models.FileField(blank=True, null=True, upload_to='regulations/', verbose_name='Файл')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='ru', max_length=5, verbose_name='Язык')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Регламент',
                'verbose_name_plural': 'Регламенты',
                'ordering': ['position'],
            },
        ),
    ]
