# Generated by Django 4.2.27 on 2026-02-25 14:45

import django.core.validators
from django.db import migrations, models
import regulations.models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0004_merge_branches'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regulation',
            options={'ordering': ['position', '-created_at'], 'verbose_name': 'Регламент', 'verbose_name_plural': 'Регламенты'},
        ),
        migrations.AlterField(
            model_name='regulation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='regulations/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'ppt', 'pptx']), regulations.models.validate_regulation_file_size], verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='type',
            field=models.CharField(choices=[('link', 'Ссылка'), ('file', 'Файл')], max_length=10, verbose_name='Тип регламента'),
        ),
    ]
