# Generated by Django 4.2.27 on 2026-03-01 12:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import regulations.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regulations', '0004_merge_branches'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regulation',
            options={'ordering': ['position', '-created_at'], 'verbose_name': 'Регламент', 'verbose_name_plural': 'Регламенты'},
        ),
        migrations.AddField(
            model_name='regulation',
            name='quiz_expected_answer',
            field=models.TextField(blank=True, help_text='If empty, non-empty user answer is enough to pass knowledge check.'),
        ),
        migrations.AddField(
            model_name='regulation',
            name='quiz_question',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='regulations/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'ppt', 'pptx']), regulations.models.validate_regulation_file_size], verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='type',
            field=models.CharField(choices=[('link', 'Ссылка'), ('file', 'Файл')], max_length=10, verbose_name='Тип регламента'),
        ),
        migrations.CreateModel(
            name='RegulationKnowledgeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('is_passed', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_checks', to='regulations.regulation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulation_knowledge_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'regulation')},
            },
        ),
    ]
