# Generated by Django 4.2.27 on 2026-03-01 18:04

import django.core.validators
from django.db import migrations, models
import regulations.models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0005_alter_regulation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='regulations/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), regulations.models.validate_regulation_file_size], verbose_name='Файл'),
        ),
    ]
