# Generated by Django 4.2.27 on 2026-02-27 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("regulations", "0005_alter_regulation_options_alter_regulation_file_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="regulation",
            name="read_deadline_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дедлайн прочтения"),
        ),
        migrations.CreateModel(
            name="RegulationQuiz",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("passing_score", models.PositiveSmallIntegerField(default=70)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "regulation",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="quiz", to="regulations.regulation"),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="RegulationQuizQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "quiz",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="regulations.regulationquiz"),
                ),
            ],
            options={"ordering": ["position", "id"]},
        ),
        migrations.CreateModel(
            name="RegulationQuizOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=500)),
                ("is_correct", models.BooleanField(default=False)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="options", to="regulations.regulationquizquestion"),
                ),
            ],
            options={"ordering": ["position", "id"]},
        ),
        migrations.CreateModel(
            name="RegulationQuizAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score_percent", models.PositiveSmallIntegerField(default=0)),
                ("passed", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "quiz",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attempts", to="regulations.regulationquiz"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="regulation_quiz_attempts", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"ordering": ["-submitted_at"]},
        ),
    ]
