# Generated by Django 4.2.27 on 2026-03-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0006_alter_regulation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='quiz_allowed_mistakes',
            field=models.PositiveSmallIntegerField(default=1, help_text='How many mistakes are allowed to pass quiz.'),
        ),
        migrations.AddField(
            model_name='regulation',
            name='quiz_questions',
            field=models.JSONField(blank=True, default=list, help_text='List of quiz questions: [{question, options: [], correct_answer}]'),
        ),
        migrations.AddField(
            model_name='regulationknowledgecheck',
            name='answers_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='regulationknowledgecheck',
            name='incorrect_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regulationknowledgecheck',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regulationknowledgecheck',
            name='total_questions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
