# Generated by Django 4.2.27 on 2026-03-03 07:03

import django.core.validators
from django.db import migrations, models
import regulations.models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0008_merge_20260302_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='regulations/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'ppt', 'pptx']), regulations.models.validate_regulation_file_size], verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='quiz_expected_answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='quiz_question',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='RegulationKnowledgeCheck',
        ),
    ]
