# Generated by Django 4.2.27 on 2026-03-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0007_regulation_quiz_allowed_mistakes_and_more'),
        ('regulations', '0009_alter_regulation_file_and_more'),
    ]

    operations = [
    ]
