# Generated by Django 4.2.27 on 2026-03-03 10:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import regulations.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regulations', '0010_merge_20260303_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulationKnowledgeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('answers_json', models.JSONField(blank=True, default=list)),
                ('score', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('incorrect_answers', models.PositiveIntegerField(default=0)),
                ('is_passed', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='regulationquizattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='regulationquizattempt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='regulationquizoption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='regulationquizquestion',
            name='quiz',
        ),
        migrations.AlterUniqueTogether(
            name='regulationreadreport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='regulationreadreport',
            name='regulation',
        ),
        migrations.RemoveField(
            model_name='regulationreadreport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='regulation',
            name='read_deadline_at',
        ),
        migrations.AddField(
            model_name='regulation',
            name='quiz_allowed_mistakes',
            field=models.PositiveSmallIntegerField(default=1, help_text='How many mistakes are allowed to pass quiz.'),
        ),
        migrations.AddField(
            model_name='regulation',
            name='quiz_questions',
            field=models.JSONField(blank=True, default=list, help_text='List of quiz questions: [{question, options: [], correct_answer}]'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='regulations/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), regulations.models.validate_regulation_file_size], verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='quiz_expected_answer',
            field=models.TextField(blank=True, help_text='If empty, non-empty user answer is enough to pass knowledge check.'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='quiz_question',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='RegulationQuiz',
        ),
        migrations.DeleteModel(
            name='RegulationQuizAttempt',
        ),
        migrations.DeleteModel(
            name='RegulationQuizOption',
        ),
        migrations.DeleteModel(
            name='RegulationQuizQuestion',
        ),
        migrations.DeleteModel(
            name='RegulationReadReport',
        ),
        migrations.AddField(
            model_name='regulationknowledgecheck',
            name='regulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_checks', to='regulations.regulation'),
        ),
        migrations.AddField(
            model_name='regulationknowledgecheck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulation_knowledge_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='regulationknowledgecheck',
            unique_together={('user', 'regulation')},
        ),
    ]
