# Generated by Django 4.2.27 on 2026-02-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ru', 'RU'), ('en', 'EN'), ('kg', 'KG')], default='ru', max_length=2),
        ),
    ]
