# Generated by Django 4.2.27 on 2026-03-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20260302_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='role',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Intern'), (20, 'Employee'), (30, 'TeamLead'), (40, 'Administrator'), (50, 'Admin'), (60, 'SuperAdmin')], default=10, verbose_name='Уровень'),
        ),
    ]
