# Generated by Codex on 2026-03-18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_merge_20260303_1327"),
        ("accounts", "0011_seed_day2_day3_tasks"),
    ]

    operations = []

