# Generated by Django 4.2.27 on 2026-02-08 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regulations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.PositiveIntegerField(unique=True, verbose_name='Номер дня')),
                ('title', models.CharField(max_length=255, verbose_name='Название дня')),
                ('goals', models.TextField(blank=True, verbose_name='Цели дня')),
                ('description', models.TextField(blank=True, verbose_name='Описание дня')),
                ('instructions', models.TextField(blank=True, verbose_name='Инструкции')),
                ('deadline_time', models.TimeField(blank=True, null=True, verbose_name='Дедлайн (ЧЧ:ММ)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('regulations', models.ManyToManyField(blank=True, related_name='onboarding_days', to='regulations.regulation', verbose_name='Регламенты')),
            ],
            options={
                'verbose_name': 'День онбординга',
                'verbose_name_plural': 'Дни онбординга',
                'ordering': ['position', 'day_number'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('done', 'Done')], default='not_started', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='onboarding_core.onboardingday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day__position', 'day__day_number'],
                'unique_together': {('user', 'day')},
            },
        ),
        migrations.CreateModel(
            name='OnboardingMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('link', 'Link'), ('video', 'Video'), ('text', 'Text'), ('image', 'Image'), ('file', 'File')], max_length=10)),
                ('content', models.TextField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='onboarding_core.onboardingday')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('day', 'position')},
            },
        ),
    ]
