# Generated by Django 6.0.1 on 2026-02-04 07:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('deadline_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'day_number'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('text', 'Text'), ('link', 'Link'), ('video', 'Video'), ('file', 'File')], max_length=16)),
                ('content', models.TextField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('onboarding_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='onboarding_core.onboardingday')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
