# Generated by Django 4.2.27 on 2026-02-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onboardingmaterial',
            options={'ordering': ['position'], 'verbose_name': 'Материал онбординга', 'verbose_name_plural': 'Материалы онбординга'},
        ),
        migrations.AlterModelOptions(
            name='onboardingprogress',
            options={'ordering': ['day__position', 'day__day_number'], 'verbose_name': 'Прогресс онбординга', 'verbose_name_plural': 'Прогресс онбординга'},
        ),
    ]
