# Generated by Django 6.0.1 on 2026-02-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_core', '0002_alter_onboardingmaterial_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingmaterial',
            name='type',
            field=models.CharField(choices=[('link', 'Link'), ('video', 'Video'), ('text', 'Text'), ('image', 'Image'), ('file', 'File')], max_length=10),
        ),
    ]
