# Generated by Django 4.2.27 on 2026-03-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0009_alter_regulation_file_and_more'),
        ('onboarding_core', '0003_merge_20260228_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onboardingday',
            options={'ordering': ['position', 'day_number'], 'verbose_name': 'Р”РµРЅСЊ РѕРЅР±РѕСЂРґРёРЅРіР°', 'verbose_name_plural': 'Р”РЅРё РѕРЅР±РѕСЂРґРёРЅРіР°'},
        ),
        migrations.AlterModelOptions(
            name='onboardingmaterial',
            options={'ordering': ['position'], 'verbose_name': 'РњР°С‚РµСЂРёР°Р» РѕРЅР±РѕСЂРґРёРЅРіР°', 'verbose_name_plural': 'РњР°С‚РµСЂРёР°Р»С‹ РѕРЅР±РѕСЂРґРёРЅРіР°'},
        ),
        migrations.AlterModelOptions(
            name='onboardingprogress',
            options={'ordering': ['day__position', 'day__day_number'], 'verbose_name': 'РџСЂРѕРіСЂРµСЃСЃ РѕРЅР±РѕСЂРґРёРЅРіР°', 'verbose_name_plural': 'РџСЂРѕРіСЂРµСЃСЃ РѕРЅР±РѕСЂРґРёРЅРіР°'},
        ),
        migrations.AlterField(
            model_name='onboardingday',
            name='day_number',
            field=models.PositiveIntegerField(unique=True, verbose_name='РќРѕРјРµСЂ РґРЅСЏ'),
        ),
        migrations.AlterField(
            model_name='onboardingday',
            name='deadline_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Р”РµРґР»Р°Р№РЅ (Р§Р§:РњРњ)'),
        ),
        migrations.AlterField(
            model_name='onboardingday',
            name='description',
            field=models.TextField(blank=True, verbose_name='РћРїРёСЃР°РЅРёРµ РґРЅСЏ'),
        ),
        migrations.AlterField(
            model_name='onboardingday',
            name='goals',
            field=models.TextField(blank=True, verbose_name='Р¦РµР»Рё РґРЅСЏ'),
        ),
        migrations.AlterField(
            model_name='onboardingday',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='Р\x98РЅСЃС‚СЂСѓРєС†РёРё'),
        ),
        migrations.AlterField(
            model_name='onboardingday',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='РђРєС‚РёРІРµРЅ'),
        ),
        migrations.AlterField(
            model_name='onboardingday',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='РџРѕСЂСЏРґРѕРє РѕС‚РѕР±СЂР°Р¶РµРЅРёСЏ'),
        ),
        migrations.AlterField(
            model_name='onboardingday',
            name='regulations',
            field=models.ManyToManyField(blank=True, related_name='onboarding_days', to='regulations.regulation', verbose_name='Р\xa0РµРіР»Р°РјРµРЅС‚С‹'),
        ),
        migrations.AlterField(
            model_name='onboardingday',
            name='title',
            field=models.CharField(max_length=255, verbose_name='РќР°Р·РІР°РЅРёРµ РґРЅСЏ'),
        ),
    ]
