# Generated by Django 4.2.27 on 2026-02-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='notificationtemplate',
            options={'verbose_name': 'Шаблон уведомления', 'verbose_name_plural': 'Шаблоны уведомлений'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('system', 'Системное'), ('learning', 'Обучение'), ('info', 'Инфо')], default='info', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='type',
            field=models.CharField(choices=[('system', 'Системное'), ('learning', 'Обучение'), ('info', 'Инфо')], max_length=50),
        ),
    ]
