# Generated by Django 4.2 on 2026-03-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="action_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="notification",
            name="code",
            field=models.CharField(default="generic.info", max_length=100),
        ),
        migrations.AddField(
            model_name="notification",
            name="entity_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="notification",
            name="entity_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="notification",
            name="severity",
            field=models.CharField(
                choices=[("info", "Info"), ("warning", "Warning"), ("critical", "Critical")],
                default="info",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["code"], name="cmn_notif_code_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["severity"], name="cmn_notif_severity_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["entity_type"], name="cmn_notif_entity_type_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["entity_id"], name="cmn_notif_entity_id_idx"),
        ),
    ]
