# Generated by Django 4.2.27 on 2026-02-17 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('did', models.TextField(verbose_name='Что сделал')),
                ('will_do', models.TextField(verbose_name='Что буду делать')),
                ('problems', models.TextField(blank=True, verbose_name='Проблемы')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('SENT', 'Отправлен'), ('ACCEPTED', 'Принят'), ('REVISION', 'На доработку'), ('REJECTED', 'Отклонён')], default='DRAFT', max_length=20, verbose_name='Статус')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='Комментарий проверяющего')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='onboarding_core.onboardingday', verbose_name='День онбординга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_reports', to=settings.AUTH_USER_MODEL, verbose_name='Стажёр')),
            ],
            options={
                'verbose_name': 'Отчёт по онбордингу',
                'verbose_name_plural': 'Отчёты по онбордингу',
                'ordering': ['day__day_number'],
            },
        ),
        migrations.CreateModel(
            name='ReportNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reports.onboardingreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Создан'), ('SENT', 'Отправлен'), ('ACCEPTED', 'Принят'), ('REVISION', 'На доработку'), ('REJECTED', 'Отклонён')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reports.onboardingreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='onboardingreport',
            index=models.Index(fields=['status'], name='reports_onb_status_91fd23_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingreport',
            index=models.Index(fields=['user'], name='reports_onb_user_id_fbaa0e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='onboardingreport',
            unique_together={('user', 'day')},
        ),
    ]
