# Generated by Django 6.0.1 on 2026-02-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_onboardingreportlog_action_reportnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportnotification',
            name='type',
            field=models.CharField(choices=[('report_submitted', 'Report submitted'), ('report_approved', 'Report approved'), ('report_revision', 'Report revision'), ('report_rejected', 'Report rejected')], default='report_submitted', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportnotification',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
