from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .frontend_compat_views import (
    FrontendAuditListAPIView,
    FrontendDepartmentsAPIView,
    FrontendDepartmentsDetailAPIView,
    FrontendFeedbackReplyAPIView,
    FrontendFeedbackTicketsAPIView,
    FrontendInstructionsAPIView,
    FrontendLoginAPIView,
    FrontendLogoutAPIView,
    FrontendMeAPIView,
    FrontendNewsCollectionAPIView,
    FrontendNewsDetailAPIView,
    FrontendOnboardingMyAPIView,
    FrontendOnboardingReportDetailAPIView,
    FrontendOnboardingReportReviewAPIView,
    FrontendOnboardingReportsAPIView,
    FrontendPositionsAPIView,
    FrontendPositionsDetailAPIView,
    FrontendPromotionRequestsActionAPIView,
    FrontendPromotionRequestsAPIView,
    FrontendRegulationsCollectionAPIView,
    FrontendRegulationsDetailAPIView,
    FrontendSchedulesHolidaysAPIView,
    FrontendSchedulesMineAPIView,
    FrontendSchedulesWorkSchedulesAPIView,
    FrontendUsersCollectionAPIView,
    FrontendUsersDetailAPIView,
    FrontendUsersSetRoleAPIView,
    FrontendUsersToggleStatusAPIView,
)

urlpatterns = [
    path("auth/login/", FrontendLoginAPIView.as_view()),
    path("auth/token/refresh/", TokenRefreshView.as_view()),
    path("auth/logout/", FrontendLogoutAPIView.as_view()),
    path("auth/me/", FrontendMeAPIView.as_view()),
    path("auth/users/", FrontendUsersCollectionAPIView.as_view()),
    path("auth/users/<int:user_id>/", FrontendUsersDetailAPIView.as_view()),
    path("auth/users/<int:user_id>/toggle_status/", FrontendUsersToggleStatusAPIView.as_view()),
    path("auth/users/<int:user_id>/set_role/", FrontendUsersSetRoleAPIView.as_view()),
    path("auth/departments/", FrontendDepartmentsAPIView.as_view()),
    path("auth/departments/<int:department_id>/", FrontendDepartmentsDetailAPIView.as_view()),
    path("auth/positions/", FrontendPositionsAPIView.as_view()),
    path("auth/positions/<int:position_id>/", FrontendPositionsDetailAPIView.as_view()),
    path("auth/promotion-requests/", FrontendPromotionRequestsAPIView.as_view()),
    path(
        "auth/promotion-requests/<int:request_id>/<str:action>/",
        FrontendPromotionRequestsActionAPIView.as_view(),
    ),
    path("core/news/", FrontendNewsCollectionAPIView.as_view()),
    path("core/news/<uuid:news_id>/", FrontendNewsDetailAPIView.as_view()),
    path("core/audit/", FrontendAuditListAPIView.as_view()),
    path("content/regulations/", FrontendRegulationsCollectionAPIView.as_view()),
    path("content/regulations/<uuid:regulation_id>/", FrontendRegulationsDetailAPIView.as_view()),
    path("content/instructions/", FrontendInstructionsAPIView.as_view()),
    path("onboarding/my/", FrontendOnboardingMyAPIView.as_view()),
    path("onboarding/reports/", FrontendOnboardingReportsAPIView.as_view()),
    path("onboarding/reports/<uuid:report_id>/", FrontendOnboardingReportDetailAPIView.as_view()),
    path("onboarding/reports/<uuid:report_id>/review/", FrontendOnboardingReportReviewAPIView.as_view()),
    path("schedules/work-schedules/", FrontendSchedulesWorkSchedulesAPIView.as_view()),
    path("schedules/user-schedules/mine/", FrontendSchedulesMineAPIView.as_view()),
    path("schedules/holidays/", FrontendSchedulesHolidaysAPIView.as_view()),
    path("feedback/tickets/", FrontendFeedbackTicketsAPIView.as_view()),
    path("feedback/tickets/<uuid:ticket_id>/reply/", FrontendFeedbackReplyAPIView.as_view()),
]
