# Generated by Django 4.2.27 on 2026-02-27 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("regulations", "0006_regulation_read_deadline_and_quiz"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegulationReadReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("report_text", models.TextField()),
                ("opened_on", models.DateField()),
                ("submitted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_late", models.BooleanField(default=False)),
                (
                    "regulation",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="read_reports", to="regulations.regulation"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="regulation_read_reports", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "unique_together": {("user", "regulation", "opened_on")},
            },
        ),
    ]
