# Generated by Django 4.2 on 2026-03-02 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("regulations", "0006_alter_regulation_file"),
        ("regulations", "0007_regulation_read_report"),
    ]

    operations = []

