# Generated by Django 4.2.28 on 2026-02-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_schedule', '0002_alter_userworkschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyworkplan',
            name='days',
            field=models.JSONField(default=list),
        ),
    ]
