# Generated by Django 4.2.27 on 2026-03-01 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_schedule', '0003_weeklyworkplan_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyWorkPlanDeadlineAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True)),
                ('missing_users', models.JSONField(default=list)),
                ('notified_admins', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Weekly plan deadline alert',
                'verbose_name_plural': 'Weekly plan deadline alerts',
                'ordering': ['-week_start'],
                'indexes': [models.Index(fields=['week_start'], name='work_schedu_week_st_919653_idx'), models.Index(fields=['created_at'], name='work_schedu_created_e43736_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyWorkPlanChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('changes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_weekly_plans_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plan_change_logs', to=settings.AUTH_USER_MODEL)),
                ('weekly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='work_schedule.weeklyworkplan')),
            ],
            options={
                'verbose_name': 'Weekly work plan change log',
                'verbose_name_plural': 'Weekly work plan change logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['week_start'], name='work_schedu_week_st_92bcd7_idx'), models.Index(fields=['user', 'week_start'], name='work_schedu_user_id_9954b3_idx'), models.Index(fields=['weekly_plan', 'created_at'], name='work_schedu_weekly__1aa76f_idx')],
            },
        ),
    ]
