# Generated by Django 4.2.27 on 2026-02-20 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCalendarDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_working_day', models.BooleanField(default=True)),
                ('is_holiday', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='attendance__date_54ebe2_idx'), models.Index(fields=['is_working_day'], name='attendance__is_work_a90c7b_idx'), models.Index(fields=['is_holiday'], name='attendance__is_holi_eba72d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('remote', 'Remote'), ('vacation', 'Vacation'), ('sick', 'Sick'), ('absent', 'Absent'), ('business_trip', 'Business trip')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marks_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_marks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'user_id'],
                'indexes': [models.Index(fields=['user', 'date'], name='attendance__user_id_757377_idx'), models.Index(fields=['date'], name='attendance__date_ef5327_idx'), models.Index(fields=['status'], name='attendance__status_c92db3_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
