# Generated by Django 4.2.27 on 2026-02-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_officenetwork'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='officenetwork',
            new_name='attendance__is_acti_78d3e3_idx',
            old_name='attendance__is_acti_0be24a_idx',
        ),
        migrations.RenameIndex(
            model_name='officenetwork',
            new_name='attendance__cidr_80bb05_idx',
            old_name='attendance__cidr_a4140a_idx',
        ),
    ]
