# Generated by Codex
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_desks(apps, schema_editor):
    Desk = apps.get_model("desks", "Desk")
    if Desk.objects.exists():
        return
    desks = []
    for row in range(1, 9):
        desks.append(Desk(code=f"L{row}", side="left", row=row))
        desks.append(Desk(code=f"R{row}", side="right", row=row))
    Desk.objects.bulk_create(desks)


def unseed_desks(apps, schema_editor):
    Desk = apps.get_model("desks", "Desk")
    Desk.objects.filter(code__in=[f"L{i}" for i in range(1, 9)] + [f"R{i}" for i in range(1, 9)]).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Desk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=10, unique=True)),
                ("side", models.CharField(choices=[("left", "Left"), ("right", "Right")], max_length=10)),
                ("row", models.PositiveSmallIntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["row", "side"],
                "unique_together": {("side", "row")},
            },
        ),
        migrations.CreateModel(
            name="DeskBooking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "desk",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bookings", to="desks.desk"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="desk_bookings", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "unique_together": {("desk", "date"), ("user", "date")},
            },
        ),
        migrations.AddIndex(
            model_name="deskbooking",
            index=models.Index(fields=["date"], name="desks_deskb_date_4c8b92_idx"),
        ),
        migrations.AddIndex(
            model_name="deskbooking",
            index=models.Index(fields=["user"], name="desks_deskb_user_7e2b5b_idx"),
        ),
        migrations.AddIndex(
            model_name="deskbooking",
            index=models.Index(fields=["desk"], name="desks_deskb_desk_9f1d7a_idx"),
        ),
        migrations.RunPython(seed_desks, unseed_desks),
    ]
