# Generated by Django 4.2.27 on 2026-03-03 07:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0004_onboardingreport_day2_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onboardingreport',
            options={'ordering': ['day__day_number'], 'verbose_name': 'Отчет по онбордингу', 'verbose_name_plural': 'Отчеты по онбордингу'},
        ),
        migrations.AddField(
            model_name='onboardingreport',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='onboarding_reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'ppt', 'pptx', 'zip', 'rar', '7z', 'png', 'jpg', 'jpeg'])], verbose_name='Вложение'),
        ),
        migrations.AlterField(
            model_name='onboardingreport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('SENT', 'Отправлен'), ('ACCEPTED', 'Принят'), ('REVISION', 'На доработку'), ('REJECTED', 'Отклонен')], default='DRAFT', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='onboardingreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_reports', to=settings.AUTH_USER_MODEL, verbose_name='Стажер'),
        ),
        migrations.AlterField(
            model_name='onboardingreportlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('SENT', 'Отправлен'), ('ACCEPTED', 'Принят'), ('REVISION', 'На доработку'), ('REJECTED', 'Отклонен')], max_length=20),
        ),
    ]
