# Generated by Django 4.2.27 on 2026-02-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrollsettings_payrollentry_worked_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollentry',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
