# Generated by Django 4.2.27 on 2026-02-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_refactor_payroll_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hourlyratehistory',
            new_name='payroll_hou_user_id_d57e8d_idx',
            old_name='payroll_hou_user_id_ba6f62_idx',
        ),
        migrations.RenameIndex(
            model_name='hourlyratehistory',
            new_name='payroll_hou_start_d_f66af6_idx',
            old_name='payroll_hou_start_d_5f1392_idx',
        ),
        migrations.RenameIndex(
            model_name='payrollrecord',
            new_name='payroll_pay_month_de0f6a_idx',
            old_name='payroll_pay_month_1bfe22_idx',
        ),
        migrations.RenameIndex(
            model_name='payrollrecord',
            new_name='payroll_pay_status_8662b7_idx',
            old_name='payroll_pay_status_7fdcf4_idx',
        ),
        migrations.RenameIndex(
            model_name='payrollrecord',
            new_name='payroll_pay_user_id_59b491_idx',
            old_name='payroll_pay_user_id_76cbf4_idx',
        ),
    ]
