# Generated by Django 4.2.27 on 2026-02-27 16:05

from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0005_rename_payroll_hou_user_id_ba6f62_idx_payroll_hou_user_id_d57e8d_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollCompensation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pay_type", models.CharField(choices=[("hourly", "Hourly"), ("minute", "Minute"), ("fixed_salary", "Fixed salary")], default="hourly", max_length=20)),
                ("hourly_rate", models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ("minute_rate", models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ("fixed_salary", models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="payroll_compensation", to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="payrollcompensation",
            index=models.Index(fields=["pay_type"], name="payroll_pay_pay_typ_7a3e31_idx"),
        ),
    ]
