# Generated by Django 4.2.27 on 2026-02-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payroll_compensation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payrollcompensation',
            new_name='payroll_pay_pay_typ_88ebb2_idx',
            old_name='payroll_pay_pay_typ_7a3e31_idx',
        ),
    ]
