# Generated by Django 4.2.27 on 2026-02-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_management',
            field=models.BooleanField(default=False, verbose_name='Руководство'),
        ),
    ]
