# Generated by Django 4.2 on 2026-02-24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_alter_feedback_options_alter_welcomeblock_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="recipient",
            field=models.CharField(
                choices=[("ADMIN", "Администратору"), ("SUPER_ADMIN", "Суперадминистратору")],
                default="ADMIN",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_feedback",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
