# Generated by Django 4.2.27 on 2026-02-17 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('work_days', models.JSONField(help_text='Список рабочих дней недели (0=Пн ... 6=Вс)')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active'], name='work_schedu_is_acti_e8d5f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductionCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_working_day', models.BooleanField(default=True)),
                ('is_holiday', models.BooleanField(default=False)),
                ('holiday_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Производственный день (РФ)',
                'verbose_name_plural': 'Производственный календарь (РФ)',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='work_schedu_date_83d630_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserWorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='work_schedule.workschedule')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['approved'], name='work_schedu_approve_bd8ca3_idx')],
            },
        ),
    ]
