# Generated by Django 4.2.28 on 2026-02-24 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userworkschedule',
            options={'verbose_name': 'График пользователя', 'verbose_name_plural': 'Графики пользователей'},
        ),
        migrations.AlterModelOptions(
            name='workschedule',
            options={'verbose_name': 'График работы', 'verbose_name_plural': 'Графики работы'},
        ),
        migrations.CreateModel(
            name='WeeklyWorkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Week start date (Monday).')),
                ('office_hours', models.PositiveSmallIntegerField(default=24)),
                ('online_hours', models.PositiveSmallIntegerField(default=0)),
                ('online_reason', models.TextField(blank=True)),
                ('employee_comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('clarification_requested', 'Clarification requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=32)),
                ('admin_comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_weekly_work_plans', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_work_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly work plan',
                'verbose_name_plural': 'Weekly work plans',
                'indexes': [models.Index(fields=['status'], name='work_schedu_status_10e877_idx'), models.Index(fields=['week_start'], name='work_schedu_week_st_8bd9c5_idx'), models.Index(fields=['user', 'week_start'], name='work_schedu_user_id_52bdf4_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='weeklyworkplan',
            constraint=models.UniqueConstraint(fields=('user', 'week_start'), name='unique_user_weekly_plan'),
        ),
    ]
